### ISSUE TITLE
Can't Download JAR, Can't Build Lienzo...

### ISSUE THREAD

**Issue by jscheller** [ahome-it/lienzo-core#103]
Hi There -

I'm trying to play with Lienzo for a project, and the link to download the jar...

http://www.emitrom.com/lienzo/download

...is 404. When I download the source here and try to build it with Gradle, I get the output below.

I'm kinda stuck. A link to the current jar file would be a big help. All of the Lienzo related links I can find for Emitrom.com seem to be dead... Is there another new location for information on this project?

Thanks for your help

Jim

---------------------
Gradle output below...

Jims-Mac:lienzo$ ~/Downloads/gradle-2.10/bin/gradle jar

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/SharedFolders/Dropbox/DW/GWT/lienzo/build.gradle' line: 79

* What went wrong:
A problem occurred evaluating root project 'lienzo'.
> Could not find property 'sonatype_snapshotURL' on org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated@52e0efd6.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.569 secs
Jims-Mac:lienzo$

**Comment by SprocketNYC** [comment]
The gradle build has our string placeholders for our repo-keys and passwords, which we REALLY wouldn't want in the build file. BUT you an just download the jar via maven? It's on the front page:

Maven:

<dependency>
  <groupId>com.ahome-it</groupId>
  <artifactId>lienzo-core</artifactId>
  <version>2.0.200-RC1</version>
</dependency>

Gradle:

dependencies {
    compile(group:'com.ahome-it',name:'lienzo-core',version:'2.0.200-RC1')
}

You can download the jar from here:

http://mvnrepository.com/artifact/com.ahome-it/lienzo-core/2.0.200-RC1

but don't forget that maven is a dependency management system, and you'll also need:

http://mvnrepository.com/artifact/com.ahome-it/ahome-tooling-nativetools/1.0.95-RELEASE

p.s. Lenzo hasn't been part of Emitrom for over 2 years... they have moved on to other things.

Dean

**Comment by jscheller** [comment]
Downloading now... Thanks Dean!
    
    Is there a canonical place now to find the Lienzo docs? What I'm
    really trying to figure out is some sort of animation chaining
    similar to what used to be possible in Raphael...
    
    
    On 12/29/15 11:00 AM, Dean Jones wrote:
    
    
      The gradle build has our string placeholders for our repo-keys
        and passwords, which we REALLY wouldn't want in the build file.
        BUT you an just download the jar via maven? It's on the front
        page:
      Maven:
      
        com.ahome-it
        lienzo-core
        2.0.200-RC1
      
      Gradle:
      dependencies {
compile(group:'com.ahome-it',name:'lienzo-core',version:'2.0.200-RC1')
        }
      You can download the jar from here:
      http://mvnrepository.com/artifact/com.ahome-it/lienzo-core/2.0.200-RC1
      but don't forget that maven is a dependency management system,
        and you'll also need:
      http://mvnrepository.com/artifact/com.ahome-it/ahome-tooling-nativetools/1.0.95-RELEASE
      p.s. Lenzo hasn't been part of Emitrom for over 2 years... they
        have moved on to other things.
      Dean
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by SprocketNYC** [comment]
The best place to look in the Kitchen Sink, which is at

https://www.lienzo-core.com/lienzo-ks

Specifically animations:

https://www.lienzo-core.com/lienzo-ks/#PLAYPEN

There is a source tab for each demo.

Also, the KS code is here:

https://github.com/ahome-it/lienzo-ks

The ( somewhat out of date ) Wiki:

https://github.com/ahome-it/lienzo-core/wiki

And the JavaDoc's

https://lienzo-core.com/documents/javadoc/lienzo-core/

**Comment by jscheller** [comment]
Thanks Dean!
    
    On 12/29/15 11:14 AM, Dean Jones wrote:
    
    
      The best place to look in the Kitchen Sink, which is at
      https://www.lienzo-core.com/lienzo-ks
      Specifically animations:
      https://www.lienzo-core.com/lienzo-ks/#PLAYPEN
      There is a source tab for each demo.
      Also, the KS code is here:
      https://github.com/ahome-it/lienzo-ks
      The ( somewhat out of date ) Wiki:
      https://github.com/ahome-it/lienzo-core/wiki
      And the JavaDoc's
      https://lienzo-core.com/documents/javadoc/lienzo-core/
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by SprocketNYC** [comment]
Hey Jim, how's everything working out for you?

**Comment by jscheller** [comment]
Slow but sure... Got lienzo building, hating Eclipse, but working
    away... See attached screenshot.
    
    Needed to add tooling-common jar as well, but figured that bit out
    on my own. Haven't gotten into the animation goals I had yet, but
    think I can see a rough path from the examples. Looks like I'm going
    to have to chain together a bunch of callbacks and build a little
    infrastructure around that...
    
    The rendering does seem a little more chunky than SVG... Like those
    circles aren't anti-aliased particularly well. Is that just the
    nature of canvas?
    
    
    On 12/30/15 1:46 PM, Dean Jones wrote:
    
    
      Hey Jim, how's everything working out for you?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by SprocketNYC** [comment]
Circles are anti-aliased fine AFAIK. Canvas should use the same underlying rendering, UNLESS you are on a highDPI device, or a low DPI screen, depends on your browser. If you check Tiger https://www.lienzo-core.com/lienzo-ks/#TIGER compared to SVG Tiger in Raphael http://raphaeljs.com/tiger.html , you'll see that Raphael actually gets it WRONG. The SVG is here https://commons.wikimedia.org/wiki/File:Ghostscript_Tiger.svg If you like, and you tell me what you are trying to do, and you have a github project, I can probably patch it up for you and get you started off on the right foot.

**Comment by jscheller** [comment]
Thanks Dean... It may be my dev setup... The whole thing is in a VM
    under Parallels right now and there seems to be more than a little
    flakiness going on, and I'm sure the screen DPI is definitely weird
    there. 
    
    Hopefully I'll get something posted publicly here in the next day or
    two... Either way I'll send you a link when I've got something live.
    :-)
    
    
    On 12/30/15 2:07 PM, Dean Jones wrote:
    
    
      Circles are anti-aliased fine AFAIK. Canvas should use the same
        underlying rendering, UNLESS you are on a highDPI device, or a
        low DPI screen, depends on your browser. If you check Tiger https://www.lienzo-core.com/lienzo-ks/#TIGER
        compared to SVG Tiger in Raphael http://raphaeljs.com/tiger.html
        , you'll see that Raphael actually gets it WRONG. The SVG is
        here https://commons.wikimedia.org/wiki/File:Ghostscript_Tiger.svg
        If you like, and you tell me what you are trying to do, and you
        have a github project, I can probably patch it up for you and
        get you started off on the right foot.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by SprocketNYC** [comment]
Yea, running in a VM the graphics drivers can definitely be flakey, especially if you consider Canvas is designed to use the GPU. So if the GPU is emulated, it will probably look crappy, so I'm guessing that is your problem. I'm using VMWare Fusion on a iMac to run Windows (7 & 10), and everything looks great, but then my iMac is a 5K and very high-res, so I'm less likely to see low-res artifacts.

I'm open to new ideas on Animation, and can probably add more TWEENER functions ( EASE_IN_OUT, etc ), and concepts in parallel and conditional chaining, intra-animation linking and feedback ( when x < 50 set color to "red" on shape s, etc ), things like Directed Acyclic Graphs, and animation story boards. Kind of a composer.

Feel free to add any ideas as an enhancement issue and I'll assign it to a future release.

As always, thanks for any feedback.

Dean

**Comment by jscheller** [comment]
Will do, Dean... I've got a number of projects planned around this tool chain, but still slowly getting back into GWT and web dev in general after having been largely away from it for a couple of years. I'm sure I'll have a few suggestions once I get my head back into the space a bit more. Appreciate all your help!

**Comment by SprocketNYC** [comment]
Cool. Closing this issue. Open another for anything more specific.

Peace!
