### ISSUE TITLE
crossorigin images no longer appear to be working (as at 2.0.270-RELEASE)

### ISSUE THREAD

**Issue by mainFC** [ahome-it/lienzo-core#125]
Hi, I had cross origin issues before as per issue #58.  These were resolved at the time.  However, I have just downloaded 2.0.270-RELEASE and there appear to be problems again.  I was previously using 2.0.114-SNAPSHOT.

This has been commented out of the ImageLoader class ...
            /*
            if (url.startsWith("http:") || (url.startsWith("https:")))
            {
                setCrossOrigin(ImageElement.as(m_image.getElement()), "anonymous");
            }
            */

This appears to cater for the problem ...
private final native void load(String url, String orig, JSImageCallback self)

but the call to it only passes an empty string as the orig value ...
load(url, "", new JSImageCallback()

Am I missing something?  How do I set crossorigin=anonymous in 2.0.270-RELEASE?

Thanks for your assistance.

**Comment by SprocketNYC** [comment]
try 2.0.271-RELEASE
