### ISSUE TITLE
Cardinal intersect

### ISSUE THREAD

**Issue by hasys** [ahome-it/lienzo-core#137]
Circles top intersect missing.

Steps To Reproduce:
1. Open "Cardinal Intersect" example of  "Wires Examples" section in Lienzo Kitchen

Actual Result:
![image](https://cloud.githubusercontent.com/assets/1477262/23067028/b7ed3976-f51d-11e6-8e7d-7352cb266c9a.png)

Expected Result:
Point on the top of circle presented as well as the others.

**Comment by danielzhe** [comment]
Fix suggestion in #210
