### ISSUE TITLE
Wires - Drag events & mouse buttons

### ISSUE THREAD

**Issue by romartin** [ahome-it/lienzo-core#145]
Drag events are always firing, no matters if left/center/right button is pressed. 
On most situations, drag handlers should only fire when the button used to start the operation is the left one.  Is that currently configurable? Review handlers  & events for this.

**Comment by romartin** [comment]
Looking a bit more, the drag operation starts due to the mouse down event is being observed in LienzoHandlerManager, and no button checks are present. So the mouse down event is always firing and resulting in a drag operation.

**Comment by Christopher-Chianelli** [comment]
Resolved in https://github.com/ahome-it/lienzo-core/pull/176

**Comment by romartin** [comment]
thanks @Christopher-Chianelli !
