### ISSUE TITLE
Wires - if you remove magnet for Sequence flow with just two magnets all diagram will disappear

### ISSUE THREAD

**Issue by hasys** [ahome-it/lienzo-core#155]
Steps to Reproduce:
1. Activate magnets on for any Sequence flow
2. Remove all magnets except Head and Tail by double-click on it
3. Remove Head or tail by double-click on it.

Actual Result:
Entire Lienzo diagram will be cleared

Expected Result:
Only active Sequence Flow will be removed

**Comment by romartin** [comment]
hey @hasys , I tested the latest `2.0.287-RELEASE` (which includes this commit) and it works, feel free to test it and close this issue please. Thanks!

**Comment by hasys** [comment]
Thank you @romartin, you are right it is fixed.
