### ISSUE TITLE
Wires - Resize magnets are not scaled on mouse enter/exit events

### ISSUE THREAD

**Issue by romartin** [ahome-it/lienzo-core#171]
The control primitives used for resize magnets are not being scaled on mouse enter/exit. 
They show behave similar as, for example, the connections, so increasing/decreasing the circle's radius as for the mouse events.

**Comment by danielzhe** [comment]
Is this one still happening? If I got it correctly, this one it's already done.

**Comment by romartin** [comment]
Yes, good point, that's already in :+1: 
Thanks!
