### ISSUE TITLE
Multipath disapears after resize

### ISSUE THREAD

**Issue by Josephblt** [ahome-it/lienzo-core#177]
After resizing using control points, multipath won't appear anymore. 

Steps to Reproduce:

1 - Open "Wirez Resize" example under "Wires Examples" section in Lienzo Kitchen
2 - Shift+Left Click on the shape
3 - Move top right point over top left point. (They have to be positioned on top of each other).
4 - Move any of the other control points.

Video: https://youtu.be/1btBZoAFJzM

**Comment by danielzhe** [comment]
Hello! I made a fix for this one. Let me now if there's something that I could improve or if it can break anything that I'm not familiar with yet. Thank you.
P.S.: I'm not sure about the coding standards you guys are following, so I've followed the coding of the classes that I changed.

**Comment by danielzhe** [comment]
I want to do more but my IntelliJ license it's about to expire in 2 days. Do you guys have some step-by-step that I can read to learn how to debug Lienzo in Eclipse? Thank you!

**Comment by helmutprovost** [comment]
Might this help?
https://stackoverflow.com/questions/18330001/super-dev-mode-in-gwt

**Comment by danielzhe** [comment]
Thanks! I did it. :)
It was easier than I thought. I was just missing one setting in Eclipse. Now it's working with break points too.
