### ISSUE TITLE
2 problems in SVGPath

### ISSUE THREAD

**Issue by yskwong** [ahome-it/lienzo-core#47]
I have upgraded my application to use Lienzo 2.0.37 Snapshot, in order to test out the features of BoundingBox and SVGPath.  The bounding box appears to be working as expected in initial rounds of  testing.  However, in importing SVG files into Lienzo using SVGPath, I encountered some unexpected outcomes - fill coloring issue and empty string exceptions.  On further investigation, I narrow the issues down to two problems, both related to SVGPath.

Problem 1:  There seems to a bug in the constructor of SVGPath (in setPath), when the path specified has multiple intervening spaces between numbers in the path definition, resulting in an empty string exception.

Problem 2:  When the path specified involves a closed path, but not with a z at the end of the path specification, filling of color of the path is not applied, and this is different from the behavior of SVG path as we can see from an example in browser (see SVG file given below)

Here are the codes illustrating these two problems, which can be run with one of the 4 lines Case 1A, 1B, 2A, 2B uncommented 
-  1A gives "NumberFormatException - empty String" error, see log below, while1B works
-  2A and 2B gives different results in filling colors, but they are the same if you view the SVG file below on a browser.  2A is what I got from the SVG file to be imported, and it is not practical for import software to put in a "z" at the end of path definition.

Thank you for your attention.

-------------------------------
public class MyJson implements EntryPoint {
	private LienzoPanel panel;
	private Layer layer;		
	@Override
	public void onModuleLoad() {
		// PRELIMINARIES
		panel = new LienzoPanel(600, 500);
		RootPanel.get().add(panel);		
		layer = new Layer();
		panel.add(layer);
		
		// TESTING
		//String pathdef = "M 488 348 A 268 80 0 1 1   -48,348 A 268 80 0 1 1   488 348z";	// CASE 1A
		//String pathdef = "M 488 348 A 268 80 0 1 1 -48,348 A 268 80 0 1 1 488 348z";		// CASE 1B

		//String pathdef = "M10,15c10,10,10,0,40,0c30,0,30,10,40,0q-10,30-40,30q-30,0-40-30";		// CASE 2A
		//String pathdef = "M10,15c10,10,10,0,40,0c30,0,30,10,40,0q-10,30-40,30q-30,0-40-30 z";	// CASE 2B

		SVGPath path = new SVGPath(pathdef);
		path.setStrokeColor(ColorName.BLACK);
		path.setFillColor(ColorName.RED);
		layer.add(path);
		
		System.out.println("Echoing layer's json: " + layer.toJSONString());
		layer.draw();		
	}	
}
--------------------
Error messages when ran with Case 1A
22:41:19.473 [ERROR] [com.xxxxx.consumer.examples.MyJson] Unable to load module entry point class com.xxxxx.consumer.examples.client.MyJson (see associated exception for details)

java.lang.NumberFormatException: empty String
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1011)
    at java.lang.Double.valueOf(Double.java:504)
    at com.ait.lienzo.client.core.shape.SVGPath.parse(SVGPath.java:118)
    at com.ait.lienzo.client.core.shape.SVGPath.setPath(SVGPath.java:504)
    at com.ait.lienzo.client.core.shape.SVGPath.&lt;init&gt;(SVGPath.java:45)
    at com.helpswitch.consumer.examples.client.MyJson.onModuleLoad(MyJson.java:30)

----------
SVG file for testing Problem 2:

\<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">
  \<path d="M10,15c10,10,10,0,40,0c30,0,30,10,40,0q-10,30-40,30q-30,0-40-30"
    stroke="black" fill="red"/>
\</svg>
-------------

**Comment by SprocketNYC** [comment]
Both should be easily fixed, just got back from the GWT.create conference a few hours ago, I'll check them and give you a 39 version later today.

**Comment by yskwong** [comment]
Great.  Thanks again for your assistance.

**Comment by SprocketNYC** [comment]
Case 2 is fixed in 39 SNAPSHOT

**Comment by yskwong** [comment]
Thanks.  Will check it out tomorrow.

**Comment by yskwong** [comment]
I have download and upgraded to 2.0.39.

Case 2 problems are indeed fixed.  Thanks.

**Comment by SprocketNYC** [comment]
Case 1A and 1B fixed in 2.0.40

**Comment by yskwong** [comment]
I tried out 2.0.40 and confirmed that the problem is fixed.  Thank you very much.
