### ISSUE TITLE
API Change: in Node.java from 2.0.37 to 2.0.40

### ISSUE THREAD

**Issue by yskwong** [ahome-it/lienzo-core#52]
I upgrade my app to 2.0.40 from 2.0.37, in order to benefit from some bug fixes in Lienzo.  I found that there is an API change in Node.java.  The following public method is no longer there in 2.0.40
    public HandlerManager getHandlerManager(){ return m_events;}

This breaks my code, and I would prefer not to spend time finding alternate ways around this change.  This method has been round for a long time sine release 1, any reason for its removal?  Can it be put back?  I think backward compatabilty in API should be given proper consideration, unless ....:)

Thank you.

**Comment by SprocketNYC** [comment]
OK, weird, I'll put it back... odd. I don't know if I had a reason

**Comment by SprocketNYC** [comment]
Fixed, use 2.0.55-SNAPSHOT

**Comment by yskwong** [comment]
Thank you very much for this extraordinary fast response.

**Comment by SprocketNYC** [comment]
I had made a change to make the creation of a HandlerManager() lazy, if you have a few thousand or more shapes, it makes a difference :-)

That method just got lost in the refactor. Thx for reporting!!!
