### ISSUE TITLE
Image won't load into Picture from AWS S3 url

### ISSUE THREAD

**Issue by mainFC** [ahome-it/lienzo-core#58]
Hi, I am really stuck with this one. I thought I had fixed it by getting the 2.0.63 snapshot but looks like its back.  It appears to be data dependent so when it went away after the .63 upgrade I think it was just because I used some different data afterwards.

So here is what is happening. I have some images in an AWS s3 bucket.  All images in the bucket are loaded into the bucket in the same way.  Most of the images will load into a Picture without any trouble but every now and then some won't.  If i upload the exact same original to S3 (it gets a different S3 url then) it will most likely work.  The same image loaded into different sizes in S3 will also generally work.  It just appears to be something random about particular uploads into S3 that then won't allow it to load into the Picture.

The images can display directly in a browser or download and show in a picture viewer without any problem.

This is one url that is failing:
https://s3.amazonaws.com/fc.dev.cnorman.lowres/view/1519-1425384073200.jpg

It will load fine into a standard GWT Image without a problem.

FireFox 25.0.1 has no problem.  Latest Chrome has the problem.  Not sure of other browsers at the moment.

This is the line to initiate the load "new Picture(url, false, null).onLoaded(plhMain);"

This is where I can track the error down to: ImageLoader class.
The onError at the bottom is being called.  But I don;t know how to debug it any further to work out what the actual error is.

Any assistance would be VERY appreciated.

    public ImageLoader(final String url)
    {
        m_image = new Image();
        m_image.setVisible(false);
        RootPanel.get().add(m_image);
        if (isValidDataURL(url))
        {
            RootPanel.get().remove(m_image);
            ImageElement.as(m_image.getElement()).setSrc(url);
            onLoad(ImageElement.as(m_image.getElement()));
        }
        else
        {
            if (url.startsWith("http:") || (url.startsWith("https:")))
            {
                setCrossOrigin(ImageElement.as(m_image.getElement()), "anonymous");
            }
            m_image.addLoadHandler(new LoadHandler()
            {
                @Override
                public void onLoad(LoadEvent event)
                {
                    RootPanel.get().remove(m_image);
                    ImageLoader.this.onLoad(ImageElement.as(m_image.getElement()));
                }
            });
            m_image.addErrorHandler(new ErrorHandler()
            {
                @Override
                public void onError(ErrorEvent event)
                {
                    RootPanel.get().remove(m_image);
                    ImageLoader.this.onError("Image " + url + " failed to load");
                }
            });

**Comment by SprocketNYC** [comment]
The basic problem is that referencing images from other machines runs afoul of the browsers/canvas Cross Origin image "tainting", basically any cross origin image drawn onto a canvas marks the canvas as "tainted", basically sets a flag that says "You drew someone else image into a Canvas and now we are going to try to stop you from manipulating it". Call it a security issue if you like, or it's a really weak stab at DRM, or whatever. NOW I TRY at best to make do, and TRY to set a crossDomain flag when loading an image, it does not work on every browser. So, you can just search for Canvas Cross Domain, CORS, etc... and you'll see the issue.

NOW, the image is coming from Amazon s3, and you can configure Amazon s3 to send the proper CORS headers! Give this a shot.

http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

**Comment by SprocketNYC** [comment]
Also, something is really weird with that image, in every browser I use, if I click or paste the link, it doesn't load the image, it DOWNLOADS it.

**Comment by mainFC** [comment]
OK, maybe some progress.  All the URLs started with "https://".  I took that off and just started them with "//" and I now do get a CORS error.
(SecurityError)@com.ait.lienzo.client.core.NativeContext2D::getImageData(DDDD)([double: 0.0, double: 0.0, double: 500.0, double: 333.0]): Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

This is the problem I had in v1.3 that was fixed.

If I prefix the url with "http:" then I get the original error, i.e. nothing, it just doesn't load.

I'll check my CORS setup on the S3 bucket.﻿

**Comment by mainFC** [comment]
OK, after some more research and testing - progress ...
The AWS S3 CORS setup was on but I added extra permission. That got over the first problem of not being able to access with the "https:" prefix.

However, after fixing that and clearing the cache, all images worked - once.  Then stopped loading and gave me the CORS security error.

I actually have the same image on the page in four different locations.  Only one of these uses lienzo.  The others all use standard GWT Image widgets.  When I remove all occurrences except for the lienzo Image everything stays working fine.  However, when I put the others back in, the Lienzo image will start getting the CORS security error again after its first attempt is successful.  Problem I guess, is that the browser is caching requests to the image with no cross origin headers.  The lienzo process then picks up that cached one instead of going to get the one it needs.

I have changed the order in the GWT code in which the URL's are set on the images and put the lienzo one first.  This seems to have fixed the problem.  I guess its a timing thing.

If this starts failing then I guess I can add the "crossOrigin" attribute to the other images as well.

I'll let you know what happens!

Thanks for the advice.﻿

**Comment by SprocketNYC** [comment]
Well, since this is clearly a CORS issue, and I allow you to set the crossOrigin property, there isn't much else I can do. Closing ticket, hope you don't mind.

p.s. try marking the images as non-cacheable.

**Comment by mainFC** [comment]
Happy to have the issue closed.  Thanks for your assistance.

P.S. Love your work!

**Comment by SprocketNYC** [comment]
Thanks! It's fun stuff!!!!
