### ISSUE TITLE
Slow Firefox performance when using image filters

### ISSUE THREAD

**Issue by mani76** [ahome-it/lienzo-core#61]
It looks like Firefox is about 3 times slower when doing image filter operations to big images compared to the Chrome and Safari which are both very FAST. Any ideas if there is anything which I can do to improve performance or is there some optimizations to do in the Lienzo core which might help?

**Comment by SprocketNYC** [comment]
I've spent HOURS in Firefox Developer Edition https://www.mozilla.org/en-US/firefox/developer/

Looking for a place to make improvements in image filters, Developer Edition has a JavaScript Profiler.

My conclusion: Anything Firefox does with Images on Canvas is just SLOW.

And perhaps worst of all, I found out recently that Firefox has a HARD limit of about 800K on data URL's, which means although it will serialize am image as a data URL, if it's over say 256x256, it likely can't read it. What makes this even worse is that Firefox, for some ungodly reason, produces data URL's for images maybe 8x larger than Chrome.

GAH!
