### ISSUE TITLE
Doubleclick incorrectly recorded

### ISSUE THREAD

**Issue by mihkell** [ahome-it/lienzo-core#67]
I made an example project where the bug comes out.
https://github.com/mihkell/lienzo-bug-example

Basiclly when I don't move my mouse after clicking on canvas and wait alittle and click again it records it as a doubleclick. Funny thing is it even doesn't record it as double click on the last item or the next, but on the third. So something gets mixed up with sending the double click event, and on what shape it thinks is being clicked on.

I have described how to see the bug in the Readme.txt in my repo.

**Comment by mihkell** [comment]
Looks like the problem is that because the X and Y coordinates stay the same, it doesn't check if the item that it's clicking on is the same or did it change.

**Comment by SprocketNYC** [comment]
Lienzo's code doesn't check if the shape is the same because the code doesn't look at the shape at all... or anything, AFAIK, because this is a native event, I'm not even trying to interpret the event until after the browser delivers it. At least not in the current codebase....

**Comment by SprocketNYC** [comment]
This looks to be a browser or GWT bug, Lienzo is not looking at event state, or event times, or looking at the last event, or last shape, or last... anything... this is a native event and other than attempting to handle double click myself, which would be a gigantic mess, there is no code I CAN change to fix this....
