### ISSUE TITLE
Where is Node.setTransform()?

### ISSUE THREAD

**Issue by mani76** [ahome-it/lienzo-core#68]
Hello,

What has happened to Node: setTransform() method?

I tried to replace all calls to Node: getAttributes().setTransform() but it did not have any effect.

**Comment by SprocketNYC** [comment]
GAHH! I truly hoped no one was using it. Working on shape intersections ( line to arc, etc ), and shape collisions, and heirarchical bounding boxes, H/V trees, etc.  The problem with setTransform() is that you could set a transform that is "non-affine", technically means that it doesn't follow the rules of http://en.wikipedia.org/wiki/Affine_transformation , which ALWAYS preserve that lines are still "parallel", as are planes and other geometry are well known. Next up in that we KNOW the order in which we apply x, y, rotation, scale, and shear. knowing these things allows us to then re-transform the intersections or collisions properly in affine space. With setTransform(), we don't really know how you arrived at the numbers and can't de-compose the order of operations. If you absolutely need setTransform() and CAN'T do it through a shape set x, y, rotation, scale, etc... then I COULD put it back, we'd just have to mark the shape outside the possibility of operations for intersections, collisions, etc...
