### ISSUE TITLE
Shapes next to LienzoPanel

### ISSUE THREAD

**Issue by BearTi** [ahome-it/lienzo-core#72]
Hi,

today I´ve tried a simple example application: I´ve draw some recangles and want to know which one was clicked. It works so far. Problem:

My recangles are next to the LienzoPanel. So I have to click on the postion, which I  marked with the red arrow to select the firstrecangle (green arrow):

![1](https://cloud.githubusercontent.com/assets/3652708/7846770/f1c0a26e-04bf-11e5-8de1-c36fc0893dc9.png)

Here is my code:

		LienzoPanel panel = new LienzoPanel(500, 500);
		panel.setBackgroundColor(Color.getRandomHexColor());
        Layer layer = new Layer();
 		panel.add(layer);

      int newXPosition = 0, positionX = 0;
      int newYPosition = 0, positionY = 0;
        
      for(int i=1; i<=5; i++){
    	  for(int j=1; j<=5; j++){
            final Rectangle rectangle = new Rectangle(15, 15);  
            rectangle.setX(positionX+newXPosition).setY(positionY+newYPosition);
            rectangle.setStrokeColor(Color.getRandomHexColor()).setFillColor(Color.getRandomHexColor()).setDraggable(true);  
            layer.add(rectangle);
            addHandler(rectangle, i, j);
			newXPosition +=25;
      	}
      	newYPosition += 30;
      	newXPosition = 0;
      }
      layer.draw();
	  deckPanel.add(panel);
      deckPanel.showWidget(0);

What is wrong? Thanks!

**Comment by SprocketNYC** [comment]
I'll check out your example and get back to you ASAP.

**Comment by BearTi** [comment]
Thanks a lot!

Maybe you need to know hoe my UIBinder looks?


<g:DockLayoutPanel unit='EM'>
	    
  		<g:north size='5'>
			<g:HTMLPanel styleName="{style.header}">
			    <g:RadioButton ui:field="add" name="yesNoButton" value="true" enabled="true">Remove</g:RadioButton>
			    <g:Button ui:field="addButton">n/a</g:Button>
				<g:Button ui:field="backButton">Refresh</g:Button>
  			</g:HTMLPanel>
  		</g:north>
  		
  		<g:center>
   			<g:DeckPanel ui:field="deckPanel" styleName="{style.content}">
   			      		    
   			</g:DeckPanel>
  		</g:center>
	</g:DockLayoutPanel>
</ui:UiBinder>

**Comment by BearTi** [comment]
Could you reproduce my problem?

**Comment by SprocketNYC** [comment]
I finally have some time to check it out. Can you try 2.0.140-RC1 first?

**Comment by BearTi** [comment]
Some Problem :-(

Maybe my Code (how I place the panel) is wrong?

**Comment by SprocketNYC** [comment]
OK, this ISN'T a Lienzo problem, really, you can tell your example has some issues, it's probably the deck panel, but it depends on the widget set being used. You create a 500x500 LienzoPanel, then set it's color, the example I expect that color was the "blue". Then you create a bunch of rectangles, and add them to the LienzoPanel, via the layer. But what you can see is that your little rectangles are not even IN the LienzoPanel, they should be in the blue box, so the events are actually correct, your widget set is drawing the LienzoPanel in the wrong place... Im not sure if it's vanilla GWT, or DeckPanel, or UI Binder that is messing up. No one has reported such a ( what would seem ) glaring bug, if you think about it.

:-)

But just to be sure, I basically re-created your code and put it in an example in the Lienzo KS,

http://www.lienzo-core.com/lienzo-ks/#RECTANGLE_CLICK_TEST

I moved the rectangles slightly, but it doesn't make any difference, they are in the LienzoPanel, clicking on them changed the color of the LienzoPanel to the same color they are filled with...

Everything seems fine.

It appears to be something in the layout of your widget set???

**Comment by BearTi** [comment]
Thanks! I will check my Code again!

**Comment by SprocketNYC** [comment]
Just a short note, LienzoPanel implements RequiredResize, ProvidesResize, so if it's containing widget is a different size ( than 500x500 ) it's probably an issue. The panel is set to 500x500 and a flag flex = false is set, so an onResize() should NOT resize the LienzoPanel(), maybe try setting it's parent to 500x500px, or add it to a SimplePanel that is 500x500 with no resize and see if that helps.

**Comment by BearTi** [comment]
I´ve solved the/my problem :-/

It was my Style Element:
<ui:style>     	
.content { 
   background-color: #eeeeee;
   text-align: center;
}

The  "text-align:center" is/was the problem.

Such a stupid mistake...

**Comment by SprocketNYC** [comment]
No problem :-) hope you are having fun with it otherwise. All tickets are closed so 2.0 RELEASE is just around the corner.

Cheers!!!
