### ISSUE TITLE
JSON Serialize and Deserialize

### ISSUE THREAD

**Issue by ResnuKrestio** [ahome-it/lienzo-core#74]
Hi,

I'm use lienzo 2.0.2 to my project
i have a problem with serialized object(Layer),  I have a group of node(rectangle etc) with a dragconstraint to snap to grid drag and a mouseEvent, when i deserialize the object, they are not snap to grid and the mouseEvent are not available, how to fix this problem?

One other problem is when i want to remove a deserialized layer object from my LienzoPanel, here is the error:
Uncaught exception escaped: com.google.gwt.event.shared.UmbrellaException
Exception caught: (NotFoundError) @com.google.gwt.dom.client.Node::removeChild(Lcom/google/gwt/dom/client/Node;)([JavaScript object(75396)]): Node was not found
See the GWT exception log for details.
Register a GWT.setUncaughtExceptionHandler(..) for custom uncaught exception handling.

what should i do to fix this problem?

Thanks before.
Resnu

**Comment by SprocketNYC** [comment]
2.0.2 is ANCIENT, one of the first snapshots. It had multiple issues that have since been fixed. Given that the current version is 2.0.117, I would update :-)
