### ISSUE TITLE
MetaData cannot be resolved

### ISSUE THREAD

**Issue by ResnuKrestio** [ahome-it/lienzo-core#75]
Hello Dean Jones,

I have update my lienzo-core to 2.0.117 version.
but my package class have an error, the error message is:
The type com.ait.tooling.native tools.client.collection.MetaData cannot be resolved. It is indirectly referenced from required .class files.

![error](https://cloud.githubusercontent.com/assets/7020875/8076201/b5ddec98-0f73-11e5-8ddc-c2915fec2998.png)

it so confusing me, can you tell me  whats going on?

Thanks
Resnu

**Comment by SprocketNYC** [comment]
I guess you are either not using maven, grade, etc, or not using them correctly. Lienzo uses 2 sub packages/jars:

https://github.com/ahome-it/ahome-tooling-nativetools

https://github.com/ahome-it/ahome-tooling-common
