### ISSUE TITLE
AlignAndDistribute with Group

### ISSUE THREAD

**Issue by christianbauer** [ahome-it/lienzo-core#77]
I'd like to draw a draggable Rectangle with some Text in it. I want to able to align these Rectangles with guides.

I'm trying to get AlignAndDistribute working with Groups and it seems like that isn't possible. A Group is not a Shape, so you can't add it to AlignAndDistribute. My attempts to fake a Shape/BoundingBox didn't work well.

If you pick one of the child shapes of the group (e.g. the Rectangle...) as an alignment bounding box, dragging a group doesn't trigger the attribute handlers of its children.

Any ideas?

**Comment by SprocketNYC** [comment]
I'll look into it, AlignAndDistribute was contributed from Red Hat, and is quite complex... let me see what I can do.

**Comment by mdproctor** [comment]
The main issue is Group at the time did not support BoundingBox. It can be made to work, if we can create a common interface that Group and Shape share. That supports BoundingBox. Like BoundingBoxable ;)

**Comment by SprocketNYC** [comment]
It's not that difficult to construct a BoundingBox for a Group, it's the sum of all the bounding boxes of everything in the Group. The issue for AlignAndDistribute is that you generally bail out if rotation, scale, or shear is set on one of the shapes..., so the question is what to do if a component of a Group is rotated, scaled, or sheared. Then we have Group's of Group's, and it's Turtles all the way down  :-)

**Comment by mdproctor** [comment]
this is now fixed
